version: '3.9'

services:
  web:
    build: .
    command: python run.py
    volumes:
      - ./:/shopapp/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - ./fashionshop/psql_data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB_NAME=fsapp

volumes:
  postgres_data: