version: '3.9'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 run:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB_NAME=fsapp
  nginx:
    build: ./fashionshop/nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: